apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service.meta.name }}
  namespace: {{ .Values.service.meta.namespace }}
spec:
  minReplicas: {{ .Values.service.meta.minReplicas }}
  maxReplicas: {{ .Values.service.meta.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service.meta.name }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.service.resources.targetAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.service.resources.targetAverageUtilization }}

